### ISSUE TITLE
Files without blank line is concatenated incorrectly

### ISSUE THREAD

**Issue by gontijolucas** [Lucasgontijo0/stubby4j-docker#1]
First file:
```yml
-  request:
      method: GET
      url: /hello-world
 
   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World!
```

Second file:
```yml
-  request:
      method: GET
      url: /hello-world-2
 
   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World 2!
```

result:
```yml
-  request:
      method: GET
      url: /hello-world
 
   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World!-  request:
      method: GET
      url: /hello-world-2
 
   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World 2!
